name: build and deploy

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      # - name: Run tests
      #   run: npm test
      - name: Package and publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PACKAGES_PAT }}
          registry: https://npm.pkg.github.com/
          check-version: true
